name: Build and push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release --output ./bin/release --version-suffix ${{ github.run_number }}
    - uses: actions/upload-artifact@v1
      with:
        name: release-0.1.0-${{ github.run_number }}
        path: ./bin/release/Cyclamen.0.1.0-${{ github.run_number }}.nupkg
    - name: Push to github
      run: dotnet nuget push ./bin/release/Cyclamen.0.1.0-${{ github.run_number }}.nupkg" --source "github" 