name: Build and push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: build
      run: dotnet build --configuration Release --output ./bin/release --version-suffix ${{ github.run_number }}
      run: dotnet build --configuration Release --version-suffix 2
    - name: upload
    - uses: actions/upload-artifact@v1
      with:
        name: art-0.1.0-${{ github.run_number }}
        path: ./bin/release
    - name: pack
      run: dotnet pack --configuration Release --output ./bin/release/packs --version-suffix ${{ github.run_number }}
    - name: push
      run: dotnet nuget push "./bin/release/packs/Cyclamen.0.1.0-${{ github.run_number }}.nupkg" --source "github"